// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserProto.proto

package com.example.demo.proto;

public interface LoginReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoginReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string phoneNum = 1;</code>
   */
  boolean hasPhoneNum();
  /**
   * <code>required string phoneNum = 1;</code>
   */
  java.lang.String getPhoneNum();
  /**
   * <code>required string phoneNum = 1;</code>
   */
  com.google.protobuf.ByteString
      getPhoneNumBytes();

  /**
   * <code>required string password = 2;</code>
   */
  boolean hasPassword();
  /**
   * <code>required string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>required string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
