// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserProto.proto

package com.example.demo.proto;

public interface LoginResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoginRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string status = 1;</code>
   */
  boolean hasStatus();
  /**
   * <code>required string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>required string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
